
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: MyVision build
on:
  push:
    branches:
    - master
    - release/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy from (source branch). # try changing the name of this folder or changing the files contents as it appears that nothing was changed
          TARGET_FOLDER: dist # The folder the action should deploy to (destination branch).